language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer require satooshi/php-coveralls:dev-master --prefer-dist --no-update --dev
  - composer install --prefer-dist --dev --no-interaction

script: ./vendor/bin/phpunit

after_script: ./vendor/bin/coveralls
